compiler/proto/field.go, compiler/proto/message_type.go
* message Type() return FQDN
* field type errors will be more accurate
=> chore(compiler): better error outputs

agent/BUILD.bazel, agent/agent.go, compiler/lib/BUILD.bazel, examples/grpc_clients/go_client/BUILD.bazel, examples/grpc_clients/go_client/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/63)
=> chore: fix duplicate import warn

BUILD.bazel, cmd/exec/BUILD.bazel, cmd/exec/main.go, docker/BUILD.bazel, exec/command.go, exec/exec.go, exec/exec_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/66)
=> fix(exec): allow set protoconf agent addr

importers/terraform_importer/meta/meta.go, importers/terraform_importer/schema_to_proto.go, importers/terraform_importer/terraform_importer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/65)
=> feat(import): add terraform std fields

compiler/lib/compiler_test.go, compiler/lib/testdata/src/test_hashable.pconf, compiler/lib/testdata/src/validator_test.pconf, compiler/proto/BUILD.bazel, compiler/proto/message.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/68)
=> feat(compiler): make proto.Message hashable

compiler/BUILD.bazel, compiler/command.go, compiler/lib/compiler.go, compiler/lib/compiler_test.go, compiler/lib/testdata/src/field_type_any_test.pconf, compiler/lib/testdata/src/test.proto, compiler/proto/message.go, utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/70)
=> fix(compiler): marshal repeated google.protobuf.Any

.bazelrc, .github/workflows/bazel.yml, .github/workflows/master.yml, .github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/72)
=> fix: master and release ci

importers/golang_importer/golang_importer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/77)
=> fix(go-importer): fix work dir for packages.Load

importers/terraform_importer/terraform_importer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/80)
=> fix(terraform): required_providers json name

BUILD.bazel, cmd/protoconf/BUILD.bazel, platforms.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/121)
=> build: multiple platforms

mkdocs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/130)
=> chore: set site url for mkdocs

.github/workflows/docs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/132)
=> fix(mkdocs): fetch all history prevent push errors

.github/workflows/docs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/133)
=> fix: docs.yml

docs/mutation-rpc.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/140)
=> docs: `mutable:` not `mutate:`

importers/terraform_importer/schema_to_proto.go
Fixes #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/147)
=> fix(terraform): some blocks might be repeated

importers/terraform_importer/schema_to_proto.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/150)
=> fix(importers): json_name on tf map fields

docs/integrations/terraform_kubernetes.md, mkdocs.yml
Add an example which shows how to create a simple Kubernetes pod with Protoconf and Terraform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/144)
=> Add Terraform Kubernetes documentation example

BUILD.bazel, cmd/protoconf/BUILD.bazel, exec/BUILD.bazel, importers/golang_importer/BUILD.bazel, importers/golang_importer/golang_importer.go, importers/terraform_importer/BUILD.bazel, importers/terraform_importer/schema_to_proto.go, importers/terraform_importer/terraform_importer_test.go, importers/wktbuilders/BUILD.bazel, importers/wktbuilders/wktbuilders.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/180)
=> fix(terraform-importer): handle `dynamic` cty type

exec/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/181)
=> fix(exec): run os.MkdirAll before writing file

importers/terraform_importer/command.go, importers/terraform_importer/terraform_importer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/186)
=> feat(terraform-importer): remote backend

compiler/lib/compiler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/187)
=> fix: prettify json

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/188)
=> chore: update deps.bzl on renovate PRs

docs/installation.md, docs/integrations/terraform.md, docs/integrations/terraform_kubernetes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/195)
=> docs: prepare docs for next version (0.1.5)

importers/terraform_importer/schema_to_proto.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/209)
=> fix(terraform-importer): `json_name` value on meta fields

compiler/lib/starlark_functions.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/212)
=> feat: allow using `module`

compiler/BUILD.bazel, compiler/command.go, compiler/template.go, consts/consts.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/protoconf/protoconf/214)
=> feat(compiler): gen pconf/pinc/mpconf files from templates

compiler/lib/starlark_loader.go, compiler/lib/testdata/src/field_type_any_test.pconf, compiler/lib/testdata/src/test.proto, compiler/starproto/any.go, compiler/starproto/enum.go, compiler/starproto/message.go
- Greater Than
- Great/Equal
- Lesser Than
- Less/Equal
=> feat(compiler): allow ENUM comparision

README.md
=> fix(docs) fix the build from source section of README to be accurate

agent/filekv/filekv.go, compiler/command.go, compiler/lib/module_service.go, compiler/lib/module_service_test.go, compiler/lib/starlark_loader.go, compiler/template.go, devserver/command.go, examples/grpc_clients/go_client/main.go, examples/mutation/go_client/main.go, importers/wktbuilders/wktbuilders.go, inserter/inserter.go, mutate/mutate.go, server/server.go, test/e2e.go, utils/testdata/embed.go
=> Improve logging  - Move to Slog fix #332
